### ISSUE TITLE
Sed fails on mac

### ISSUE THREAD

**Issue by qwitwa** [zanaca/docker-dns#4]
@sed -i s/\s#bind-interfaces// $(DNSMASQ_LOCAL_CONF) fails on mac with the following error https://stackoverflow.com/questions/35620009/sed-extra-characters-at-end-of-l-command

**Comment by zanaca** [comment]
👍 
Thank you  for reporting! It was fixed in 8f018d3dc2d5b43591ebb28480433d34086e2e72!
